"""Documentation ORM model — generated markdown for a code entity."""

from __future__ import annotations

from datetime import datetime

from sqlalchemy import DateTime, ForeignKey, Integer, String, Text, func
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.core.database import Base


class Documentation(Base):
    """Generated documentation for a single code entity.

    A new row supersedes the previous one for the same entity; ``version`` is
    incremented so prior drafts remain available for history/diffing.
    """

    __tablename__ = "documentation"

    id: Mapped[int] = mapped_column(primary_key=True)
    repository_id: Mapped[int] = mapped_column(
        ForeignKey("repositories.id", ondelete="CASCADE"), index=True
    )
    entity_id: Mapped[int] = mapped_column(
        ForeignKey("code_entities.id", ondelete="CASCADE"), index=True, unique=True
    )

    content_markdown: Mapped[str] = mapped_column(Text, default="")
    summary: Mapped[str | None] = mapped_column(Text, default=None)
    version: Mapped[int] = mapped_column(Integer, default=1)

    # Where the markdown was written on disk (docs_storage).
    storage_path: Mapped[str | None] = mapped_column(String(1024), default=None)

    # "ai" when generated by the LLM, "fallback" when AI was unavailable.
    generator: Mapped[str] = mapped_column(String(32), default="ai")

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), onupdate=func.now()
    )

    entity: Mapped["CodeEntity"] = relationship(  # type: ignore[name-defined]
        back_populates="documentation"
    )
